/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "status-honeycomb": {
    name: "status-honeycomb",
    description: "Dense microservice health visualization with 100+ cells showing instance/pod status in a compact honeycomb grid",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/status-honeycomb.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/status-honeycomb.tsx")
      return { default: mod.StatusHoneycomb || mod.default }
    }),
  },
  "status-honeycomb-demo": {
    name: "status-honeycomb-demo",
    description: "Demo for StatusHoneycomb component",
    type: "registry:example",
    registryDependencies: ["status-honeycomb"],
    files: [
      {
        path: "registry/default/ui/status-honeycomb.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/status-honeycomb-demo.tsx")
      return { default: mod.default }
    }),
  },
  "trace-breadcrumb": {
    name: "trace-breadcrumb",
    description: "Horizontal trace timeline showing request flow through microservices with time spent in each service",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/trace-breadcrumb.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/trace-breadcrumb.tsx")
      return { default: mod.TraceBreadcrumb || mod.default }
    }),
  },
  "trace-breadcrumb-demo": {
    name: "trace-breadcrumb-demo",
    description: "Demo for TraceBreadcrumb component",
    type: "registry:example",
    registryDependencies: ["trace-breadcrumb"],
    files: [
      {
        path: "registry/default/ui/trace-breadcrumb.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/trace-breadcrumb-demo.tsx")
      return { default: mod.default }
    }),
  },
  "latency-flame-compact": {
    name: "latency-flame-compact",
    description: "Horizontal flame graph strip for trace spans with stacked bars by duration and depth coloring",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/latency-flame-compact.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/latency-flame-compact.tsx")
      return { default: mod.LatencyFlameCompact || mod.default }
    }),
  },
  "latency-flame-compact-demo": {
    name: "latency-flame-compact-demo",
    description: "Demo for LatencyFlameCompact component",
    type: "registry:example",
    registryDependencies: ["latency-flame-compact"],
    files: [
      {
        path: "registry/default/ui/latency-flame-compact.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/latency-flame-compact-demo.tsx")
      return { default: mod.default }
    }),
  },
  "health-gauge": {
    name: "health-gauge",
    description: "Vertical segmented rack light gauge for CPU/MEM/Disk/Load with signal glow on thresholds",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/default/ui/health-gauge.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/health-gauge.tsx")
      return { default: mod.HealthGauge || mod.default }
    }),
  },
  "health-gauge-demo": {
    name: "health-gauge-demo",
    description: "Demo for HealthGauge component",
    type: "registry:example",
    registryDependencies: ["health-gauge"],
    files: [
      {
        path: "registry/default/ui/health-gauge.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/health-gauge-demo.tsx")
      return { default: mod.default }
    }),
  },
}
